spring:
  # RabbitMQ配置项，对应RabbitProperties配置类
  rabbitmq:
    host: localhost     # rabbitmq的服务地址
    port: 5672          # 服务端口
    username: guest     # rabbitmq的登陆账号
    password: guest     # 登陆密码
    listener:
      simple:
        prefetch: 1     # 设置预读取数，消费端消费完特定数目消息后消费端才能拿取消息，此配置用于保证公平转发；是全局的。